#!/bin/bash

minsize=10
inc=16
P=10
#maxsize=$(echo 2048+$P | bc)
maxsize=52
rm -f *.dat
tam_2=$(echo "$((8 * 1024))" | bc -l)
echo $tam_2
tam=$(echo "$j*$P*1024" | bc -l)
for i in $(seq $minsize $inc $maxsize)
do
	echo -n -e "\r$i"
	tnorm=$(valgrind --tool=cachegrind ./mult_norm $i 2>&1) 
	tgreat=$(valgrind --tool=cachegrind ./mult_great $i 2>&1)
	tnorm=$(echo $tnorm | awk -v FS="+" '{print $2}' | awk -v FS=" " '{print $1}' | sed 's/,//g')
	tgreat=$(echo $tgreat | awk -v FS="(" '{print $2}' | awk -v FS=" " '{print $1}' | sed 's/,//g')
	echo $i $tnorm $tgreat >> 'tamCache_'$tam'.dat'
done