#!/bin/bash

minsize=10
inc=16
maxsize=2058
rm -f *.dat

for i in $(seq $minsize $inc $maxsize)
do
	echo -n -e "\r$i"
	tslow=$(valgrind --tool=cachegrind ./slow $i 2>&1 > /dev/null | grep 'D1' | head -n 1 | awk '{print $6"\t"$9}')
	tfast=$(valgrind --tool=cachegrind ./fast $i 2>&1 > /dev/null | grep 'D1' | head -n 1 | awk '{print $6"\t"$9}')
	echo $i $tslow $tfast >> 'tamCache.dat'
done